
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
  <head>
  <meta charset="utf-8" />

  <meta name="author" content="Harrison Weir"/>
  <meta name="subject" content="Cats. Their Varieties, Habits and Management; and for show, the Standard of Excellence and Beauty"/>
  <meta name="keywords" content="cats,feline"/>
  <meta name="date" content="2014-12-05"/>
  </head>
  <body>
    <div class="frontcover">
    </div>
    <div class="contents">
        <div class="row">
            <div class="column">
                <img  src="data:image/png;base64,<?php echo base64_encode(file_get_contents(base_path('public/images/settings/'.$setting->company_logo))); ?>" width="80 px;">
            </div>
            <div class="column" style="margin-top: -15px; margin-bottom: 30px;">
                <h3>{{ $setting->company_title}}</h3>
                <p>{{ $setting->company_address}}</p>
                <p>Email : {{ $setting->company_email}}</p>
                <p>Phone : {{ $setting->company_phone}}</p>
            </div>

        </div>

        <div class="panel-heading row">
            <div style="float: left;">
                <h4><b>Leave Application Form</b></h4>
            </div>

            <div class="panel-heading" style="float: right;margin-top:-8px;">
                <h4><b>Date : {{date('d-m-Y')}}</b></h4>
            </div>
        </div>

        <br>

        <table>
            <tr>
                <td><b>Employee Name </b>: {{$leave_application->employee->first_name.' '.$leave_application->employee->last_name}}</td>
                <td><b>Employee ID </b>: {{$leave_application->employee->employee_manual_id}}</td>
            </tr>
            <br>
            <tr>
                <td><b>Designtation </b>: {{$leave_application->employee->designation->designation_name}}</td>
                <td><b>Department </b>: {{$leave_application->employee->department->department_name}}</td>
            </tr>
            <br>
            <tr>
                <td><b>Leave From </b>:  {{ \Carbon\Carbon::parse($leave_application->start_date)->format('d-m-Y')}}</td>
                <td><b>To </b>: {{ \Carbon\Carbon::parse($leave_application->end_date)->format('d-m-Y')}}</td>
            </tr>
            <br>
            <tr>
                <td><b>Leave Type </b>: {{$leave_application->leave_type->leave_name}}</td>
                <td><b>No. of Days </b>: {{$leave_application->no_of_days}}</td>
            </tr>
        </table>

        <!-- resone -->
        <br>

        <div class="col-8 col-md-4" style="height: 200px; width: auto; font-size: 15px;">
            <b>Reason:</b> <br>
            <p style="text-align: justify;">
                {!! $leave_application->reason !!}
            </p>

        </div>

        <div class="row">
            <div class="column">
                <p>...................</p>
                <p>Employee Signature: </p>
            </div>

            <div class="column" style="text-align: center;">
                <p>...................</p>
                <p>Approved By: </p>
                <p>{{$leave_application->approved_employee->first_name.' '.$leave_application->approved_employee->last_name}} </p>
                <p>{{$leave_application->company->comp_name}}</p>
            </div>
        </div>

        <div style="margin-top: 80px; text-align: center; font-size: 12px;">
            <p class="text-center">Generated By - <a> Polock Group</a></p>
        </div>

    </div>


  </body>
</html>


<style>
    table { font-size: 15px; }
    td    { margin-top: 10px; }
    tr    { page-break-inside:30px; margin: 5px; }

    .column {
        margin-top: 20px;
        float: left;
        width: 50%;
        padding: 5px;
    }

    .column p{
        margin: 1px;
        font-size: 14px;
    }

    .row:after {
        content: "";
        display: table;
        clear: both;
    }

    @page {
        size: A4;
        margin: 20pt 40pt 40pt;
    }

    @page:first {
    size: 5.5in 8.5in;
    margin: 0;
    }

</style>
