@extends('layouts.admin')
@section('content')
    <div class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                      Bank Payslip | Financial Year <?php echo date("Y"); ?>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table id="salaryGenerate" class=" table table-bordered table-striped table-hover datatable datatable-LeaveApplication">
                                <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>Salary Month</th>
                                    <th>Generated By</th>
                                    <th>Generated Date</th>
                                    <th>Action</th>

                                </tr>
                                </thead>
                                <tbody>
                                @foreach($salaries as $key=> $val)
                                @php 
                                    $month = Carbon\Carbon::parse($val->month)->format('M Y');
                                    $month_year = Carbon\Carbon::parse($val->month)->format('Y-m');
                                    $start_date = $month_year.'-'.'01';
                                    $end_date = $month_year.'-'.'31';
                                    $salaryGenarate= \App\Models\SalaryGenerate::where('generate_date','>=',$start_date)->where('generate_date','<=',$end_date)->first();
                                 @endphp
                                    <tr data-entry-id="">
                                        <td></td>
                                        <td>{{ $month }}</td>
                                        <td>{{ $salaryGenarate->user->name}}</td>
                                        <td>{{ $salaryGenarate->generate_date}}</td>
                                        <td>
                                            <a class="icon" href="{{ route('admin.payroll.salaryChart', $month_year) }}" title="Salary Chart"><i class="fa fa-bars"></i></a>
                                            <a class="icon" href="{{ route('admin.payroll.bankPayslip', $month_year) }}" title="Payslip Record"><i class="fa fa-file-text" aria-hidden="true"></i></a>
                                        </td>
                                    </tr>

                                    @endforeach
                                
                                </tbody>
                            </table>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    @parent
    <script>
        $(function () {
            let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
            @can('leave_application_delete')
            let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
            let deleteButton = {
                text: deleteButtonTrans,
                url: "{{ route('admin.leave-applications.massDestroy') }}",
                className: 'btn-danger',
                action: function (e, dt, node, config) {
                    var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
                        return $(entry).data('entry-id')
                    });

                    if (ids.length === 0) {
                        alert('{{ trans('global.datatables.zero_selected') }}')

                        return
                    }

                    if (confirm('{{ trans('global.areYouSure') }}')) {
                        $.ajax({
                            headers: {'x-csrf-token': _token},
                            method: 'POST',
                            url: config.url,
                            data: { ids: ids, _method: 'DELETE' }})
                            .done(function () { location.reload() })
                    }
                }
            }
            dtButtons.push(deleteButton)
            @endcan
            $.extend(true, $.fn.dataTable.defaults, {
                orderCellsTop: true,
                order: [[ 1, 'desc' ]],
                pageLength: 100,
            });
            let table = $('.datatable-LeaveApplication:not(.ajaxTable)').DataTable({ buttons: dtButtons })
            $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
                $($.fn.dataTable.tables(true)).DataTable()
                    .columns.adjust();
            });

        })

    </script>

    <script>
        function rejectFunction() {
            if(!confirm("Are You Sure to Reject ?"))
                event.preventDefault();
        }
    </script>

    <script>
        function approveFunction() {
            if(!confirm("You are going to Approve !"))
                event.preventDefault();
        }
    </script>
@endsection

<style>
    /* CSS for action icons */
    .icon {
        background: #ffc0c0;
        width: 25px;
        height: 15px;
        border-radius: 50%;
        text-align: center;
        line-height: 40px;
        vertical-align: middle;
        padding: 5px;
        color: black;
    }
</style>
